% % % % % % % % % % % 
% % % % % % % % % % % 
% Structure data
% 
%   data.subjects 
%   data.dcm_bold_folders
%   data.nii_bold_folders
% 
% 
% 

data.dcm_folder = '/media/borear/Projects/cardio/dicom_ready/';

data.main_folder = '/media/borear/Projects/cardio/preprocessing_spm12_v2016/';

data.subjects   =   {'HC_AM32', ...
                     'HC_BLQ06', ...
                     'HC_CL21', ...
                     'HC_DF02', ...
                     'HC_EG53', ...
                     'HC_FC34', ...
                     'HC_FT50', ...
                     'HC_GB18', ...
                     'HC_JGC42', ...
                     'HC_JPD03', ...
                     'HC_JT15', ...
                     'HC_LC33', ...
                     'HC_LD52', ...
                     'HC_MB08', ...
                     'HC_MT01', ...
                     'HC_MTC16', ...
                     'HC_PV41', ...
                     'HC_RC35', ...
                     'HC_US60', ...
                     'HC_YD19', ...
                     'PD_AH40', ...
                     'PD_DC17', ...
                     'PD_GL29', ...
                     'PD_JAS30', ...
                     'PD_JC09', ...
                     'PD_JP61', ...
                     'PD_JW28', ...
                     'PD_LLT37', ...
                     'PD_MG48', ...
                     'PD_MP31', ...
                     'PD_NM12', ...
                     'PD_PE24', ...
                     'PD_PS26', ...
                     'PD_RCG39', ...
                     'PD_RG13', ...
                     'PD_RP36', ...
                     'PD_RR11', ...
                     'PD_SE55', ...
                     'PD_WR27', ...
                     'PD_M_CT02', ...
                     'PD_M_EC03'                     
                    };

data.hcsubjects   =   {'HC_AM32', ...
                     'HC_BLQ06', ...
                     'HC_CL21', ...
                     'HC_DF02', ...
                     'HC_EG53', ...
                     'HC_FC34', ...
                     'HC_FT50', ...
                     'HC_GB18', ...
                     'HC_JGC42', ...
                     'HC_JPD03', ...
                     'HC_JT15', ...
                     'HC_LC33', ...
                     'HC_LD52', ...
                     'HC_MB08', ...
                     'HC_MT01', ...
                     'HC_MTC16', ...
                     'HC_PV41', ...
                     'HC_RC35', ...
                     'HC_US60', ...
                     'HC_YD19', ...
                    };                

data.pdsubjects   =   {'PD_AH40', ...
                     'PD_DC17', ...
                     'PD_GL29', ...
                     'PD_JAS30', ...
                     'PD_JC09', ...
                     'PD_JP61', ...
                     'PD_JW28', ...
                     'PD_LLT37', ...
                     'PD_MG48', ...
                     'PD_MP31', ...
                     'PD_NM12', ...
                     'PD_PE24', ...
                     'PD_PS26', ...
                     'PD_RCG39', ...
                     'PD_RG13', ...
                     'PD_RP36', ...
                     'PD_RR11', ...
                     'PD_SE55', ...
                     'PD_WR27', ...
                    };      

data.hcrfx = {'rfx_hc'};                

data.pdrfx = {'rfx_pd'};                

data.pdmusicrfx = {'rfx_pdmusic'}; 

data.pdmusicsubjects   =   {'PD_M_CT02', ...
                            'PD_M_EC03'                     
                            };                
                
data.dcm_anat_folder = 'anat';
data.output = {'Outputs'};
                
data.dcm_bold_folders = {'task/bold/'};
                
data.nii_bold_folders = {'task/bold'};


data.sess = {'sess1', ...
             'sess2'};
                
data.fieldmap = {'task/mag', ...
                 'task/phase'};

data.echo = {'echo_7.38'};                 

data.ffx = {'ffx'};

data.onset = {'onset'};

if ~exist(data.main_folder,'dir') 
    mkdir(data.main_folder) 
end


for nSub=1:length(data.subjects)
    if ~exist(fullfile(data.main_folder,data.subjects{nSub}),'dir') 
        mkdir(fullfile(data.main_folder,data.subjects{nSub}));
    end
    for nSess=1:length(data.sess)
        if ~exist(fullfile(data.main_folder,data.subjects{nSub},data.sess{nSess}),'dir') 
            mkdir(fullfile(data.main_folder,data.subjects{nSub},data.sess{nSess}));
        end
    end
end

